[project]
name = "home-salamat"
version = "1.0.0"
description = "Home Salamat - Health App"
requires-python = ">=3.10"
dependencies = ["flet==0.28.3"]

[tool.flet]
product = "Home Salamat"
org = "ir.karaj.health"
bundle_id = "ir.karaj.health.homesalamat"
build_number = 1

[tool.flet.app]
path = "."

[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.CALL_PHONE" = true